---
title: "Synthetic DID"
author: "Marziyeh Aghaei"
date: "05/19/2024"
output:
  html_document: 
    code_folding: show
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,message = FALSE}
# packages
require(tidyverse)
require(fixest)
require(stargazer)
require(haven)
library(Synth)
library(usethis)
library(synthdid)
library(dplyr)
library(foreign)
library(gridExtra)
library(ggplot2)
library(openxlsx)

# clear
rm(list = ls())

# set directories
directory_specific <-"C:/Users/rbm7796/Dropbox/FDC_IQVIA"
directory_data <- file.path(directory_specific,"/Stata/IntermData")

# Load Data

setwd(directory_data)
# df <- read_dta("data_cleaned_for_synthetic_molecule.dta") 
df <- read_dta("data_cleaned_for_synthetic_molecule_hospital.dta") 
df <- df[order(df$country,df$molecule,df$month),]
df <- subset(df, is.na(supplement))

# df_cont <- read_dta("data_donor_pool_long.dta") 
df_cont <- read_dta("data_donor_pool_long_hospital.dta") 
df_cont <- subset(df_cont, is.na(supplement))

```

```{r}
df_cont$sales<-log(df_cont$sales)
df_cont$price<-log(df_cont$price)

df$sales_total<-log(df$sales_total)
df$price_total<-log(df$price_total)

df_treat <- df %>% select(country, molecule, month,sales_total,price_total,generic_entry, atc4)
df_treat <- na.omit(df_treat)

# remove if generic has been on the market less than 8 months
df_treat <- df_treat[df_treat$generic_entry<=60,]

```


# Function for SDID estimation

The function provides estimates for synthetic DID for country-molecule level.

```{r}
# function
func_sdid <-  function(dependent_var_treat, dependent_var_cont, country_c, molecule_d, data_treat, data_cont){
  
# part 1: data cleaning
  
  # choose treatment obs
  data_treat_cd <- data_treat %>% 
    filter(country == country_c) %>% filter(molecule == molecule_d)
  
  # observation of months that have obs of c-d
  month_cd <- unique(data_treat_cd$month)
  
  # generic entry
  generic_entry_cd <- unique(data_treat_cd$generic_entry)
  
  # obtain atc4 for molecule
  atc4_d <- unique(data_treat_cd$atc4)
  
  # choose control obs
  # choose obs with no missing month
    
  data_cont_cd <- data_cont %>% 
    filter(sales_month == 68) %>% 
    filter(atc4 != atc4_d) %>%
    filter(month %in% month_cd) %>% 
    filter(country == country_c) 
  
  # choose variables
  data_treat_cd <- data_treat_cd %>% 
    select(month, molecule, dependent_var_treat)
  
  
  data_cont_cd <- data_cont_cd %>% 
    select(month, molecule, dependent_var_cont)
  
  # rename to merge with the treatment dataset
  colnames(data_cont_cd)[colnames(data_cont_cd) == dependent_var_cont] <- dependent_var_treat
  
  # merge: put all obs (treatment and control) next to each other
  data_panel_cd <- bind_rows(data_treat_cd, data_cont_cd) 
  
# Part 2: prepare data format for SDID
# order data such that data from a specific period be next to each other, with the treated one shows at last. treatment_group and treated are just intermediate variables for constructing treat variable. The treat variable equals 1 for the treated group, after the generic entry, and 0 otherwise.
  
    data_panel_sdid <- data_panel_cd %>% 
    group_by(molecule) %>% 
    mutate(id = cur_group_id()) %>% 
    ungroup() %>% 
    as.data.frame() %>% 
    mutate(id = as.numeric(id),
    month = as.numeric(month)) %>%
    mutate(treatment_group = ifelse(molecule == molecule_d, 1, 0)) %>%
    mutate(post_treatment = ifelse(month >= generic_entry_cd,1, 0))%>%
    mutate(treated = treatment_group * post_treatment)
  
# first order by month, to put data from a similar month next to each other, and then order by treatment group, to put the treatment group at last
  
    data_panel_sdid<- data_panel_sdid[order(data_panel_sdid$month,data_panel_sdid$treatment_group), ]%>%
    select(molecule,month,dependent_var_treat,treated)
    
    # check whether it is balanced and remove controls that make it unbalanced
    data_panel_sdid<- data_panel_sdid %>% group_by(molecule) %>% filter(n() == length(month_cd)) %>% ungroup()
    
    # convert the treated column to a logical variable
    data_panel_sdid_logical<-data_panel_sdid
    data_panel_sdid_logical$treated<-as.logical(data_panel_sdid$treated)

# part 3: use the prepared data and do SDID
  
# the following functions are from SDID package in R. 
    data_panel_sdid_logical <<-data_panel_sdid_logical
    binary_mat<-panel.matrices(as.data.frame(data_panel_sdid_logical))
    
    # synthdid_estimate gets inputs from panel.matrices
    
    if(binary_mat$N0<4){
      print("****")
      results<-list(estimate='Nan',mat='Nan')
      return(results)
   }
    
    estimate = synthdid_estimate(binary_mat$Y, binary_mat$N0, binary_mat$T0)
    results<-list(estimate=estimate,mat=data_panel_sdid)
    return(results)
}  
```


```{r}
# loop for synthetic DID for country-molecule
dependent_var_sales <- "sales_total"
dependent_var_price <- "price_total"

country_list<-unique(df_treat[,1])
pos<-0
counter<-0

for (j in 1:nrow(country_list)){
  
  print(paste("Running SDID for Country",j))
  country_c <- country_list$country[j]
  
  # extract list of molecules for country_c
  molecule_list <- unique(df_treat[df_treat[,1] == country_c,2])
  
  for (i in 1:nrow(molecule_list)) {
    molecule_d=molecule_list$molecule[i]
  
    # Get SDID results for sales1 and price1

    sdid_res_sales<-func_sdid(dependent_var_sales,"sales", country_c, molecule_d, df_treat, df_cont)
    
    sdid_res_price<-func_sdid(dependent_var_price,"price", country_c, molecule_d, df_treat, df_cont)
    
    if (sdid_res_sales$estimate=='Nan' || sdid_res_price$estimate=='Nan'){
      counter<-counter+1
      print(counter)
    }
    # check if there is any results for SDID
    if (sdid_res_sales$estimate!='Nan' && sdid_res_price$estimate!='Nan'){
      
      # The SDID package provides SDID plot and weights for the elements in the control group, but it does not provide values for the constructed parallel trend. So here, I extract weights and reconstruct the parallel trend by taking a weighted average over controls
      
      # get weights for controls in SDID
      sdid_res_sales_weights<-synthdid_controls(sdid_res_sales$estimate, sort.by = 1, mass = 0.9, weight.type = "omega")
      sdid_res_sales_weights<-data.frame(sdid_res_sales_weights)
      sdid_res_sales_weights$molecule <- row.names(sdid_res_sales_weights)
      
      # recover the control group
      sdid_res_sales_controlgroup <- sdid_res_sales$mat
 
      sdid_res_sales_mat <- merge(sdid_res_sales_controlgroup, sdid_res_sales_weights, by ="molecule", all.x = TRUE)
      
      # The resulting mat has sales and weights columns (named estimate), so we need to multiply these two columns
      sdid_res_sales_mat$product<-sdid_res_sales_mat[[dependent_var_sales]] * sdid_res_sales_mat$estimate
      # and take sum over results by month, the result is the weighted average that we needed
      sdid_res_sales_mat <- sdid_res_sales_mat %>%group_by(month) %>%summarize(sales_control = sum(product,na.rm=TRUE))
      
      results_cd_mat <- sdid_res_sales_mat %>% select(month,sales_control)
      
      # now redo all I did for sales for prices
      # get weights for controls in SDID
      sdid_res_price_weights<-synthdid_controls(sdid_res_price$estimate, sort.by = 1, mass = 0.9, weight.type = "omega")
      sdid_res_price_weights<-data.frame(sdid_res_price_weights)
      sdid_res_price_weights$molecule <- row.names(sdid_res_price_weights)
      
      # merge it with the mat, which contains sales for the controls
      sdid_res_price_controlgroup<-sdid_res_price$mat

      sdid_res_price_mat <- merge(sdid_res_price_controlgroup, sdid_res_price_weights, by ="molecule", all.x = TRUE)
      
      # The resulting mat has price and weights columns (named estimate), so we need to multiple these two columns
      sdid_res_price_mat$product<-sdid_res_price_mat[[dependent_var_price]] * sdid_res_price_mat$estimate
      # and take sum over results by month, the result is the weighted average that we needed
      sdid_res_price_mat <- sdid_res_price_mat %>%group_by(month) %>%summarize(price_control = sum(product,na.rm=TRUE))
      
      # and here is all I need for price, that is price for treated group, and price for control group for post period
      results_mat_price <- sdid_res_price_mat %>% select(month,price_control)
      results_cd_mat <- merge(results_cd_mat, results_mat_price, by = "month", all.x = TRUE)
      results_cd_mat <- results_cd_mat %>% select(month,price_control,sales_control)
      
      results_cd_mat$molecule<-molecule_d
      results_cd_mat$country<-country_c
      results_cd_mat$ncontrol_sales <- length(sdid_res_sales_weights$molecule)
      results_cd_mat$ncontrol_price <- length(sdid_res_price_weights$molecule)
      
      pos=pos+1
      
      if (pos==1){
      results_mat<-results_cd_mat} else if (pos>1) {
        results_mat<-rbind(results_mat,results_cd_mat)
      }
    }
  }
}


```
```{r}
mat_final <- merge(df,results_mat,by=c("country","molecule","month"),all.x=TRUE)
mat_final <- mat_final[order(mat_final$country,mat_final$molecule,mat_final$month),]
mat_final <- mat_final %>% select(-sales_total,-price_total,-revenue_total)
```
```{r}
setwd(directory_data)
write_dta(mat_final, "SDID_log_hospital_donorpool_hospital.dta")
```

```{r}
setwd(directory_data)
mat_final <- merge(df,results_mat,by=c("country","molecule","month"),all.x=TRUE)
mat_final <- mat_final[order(mat_final$country,mat_final$molecule,mat_final$month),]

mat_final$sales0 <- log(mat_final$sales0)
mat_final$sales1 <- log(mat_final$sales1)
mat_final$price0 <- log(mat_final$price0)
mat_final$price1 <- log(mat_final$price1)

write_dta(mat_final, "SDID_log_hospital_donorpool_hospital.dta")

setwd(file.path(directory_specific,"/Graphs/"))
country_list<-unique(mat_final[,1])
for (j in 1:length(country_list)){
  country_c <- country_list[j]
  # extract list of molecules for country_c
  molecule_list <- unique(mat_final[mat_final$country == country_c,2])
  mat_final_c <- mat_final[mat_final$country==country_c,]
  for (i in 1:length(molecule_list)) {
    molecule_d=molecule_list[i]
    mat_final_cd <- mat_final_c[mat_final_c$molecule==molecule_d,]
    
    plot_sales <- ggplot(data = mat_final_cd, aes(x = month)) + 
    geom_line(aes(y = sales_total, colour = "Treatment")) + 
    geom_line(aes(y = sales_control, colour = "Control")) +
    geom_vline(xintercept = as.numeric(unique(mat_final_cd$generic_entry)), linetype = "dashed", color = "green") +
    labs(title = paste("n controls", mat_final_cd$ncontrol_sales), x = "Month", y = "Sales") +
    scale_colour_manual(values = c("Treatment" = "blue", "Control" = "red")) +
    theme()
    ggsave(filename = file.path("SDID_log_hospital_donorpool_hospital", paste0(country_c,"_", molecule_d, "_sales.png")), plot = plot_sales, width = 10, height = 6)
    
    plot_price <- ggplot(data = mat_final_cd, aes(x = month)) + 
    geom_line(aes(y = price_total, colour = "Treatment")) + 
    geom_line(aes(y = price_control, colour = "Control")) +
    geom_vline(xintercept = as.numeric(unique(mat_final_cd$generic_entry)), linetype = "dashed", color = "green") +
    labs(title = paste("n controls", mat_final_cd$ncontrol_price), x = "Month", y = "Price") +
    scale_colour_manual(values = c("Treatment" = "blue", "Control" = "red")) +
    theme()
    ggsave(filename = file.path("SDID_log_hospital_donorpool_hospital", paste0(country_c,"_", molecule_d,"_price.png")), plot = plot_price, width = 10, height = 6)
  }
}
```

```{r}
setwd(directory_data)
mat_final <- read_dta("data_cleaned_for_synthetic_molecule_hospital_with_sdidres_log.dta")
mat_final$sales0 <- log(mat_final$sales0*100000)
mat_final$sales1 <- log(mat_final$sales1*100000)
mat_final$price0 <- log(mat_final$price0*100000)
mat_final$price1 <- log(mat_final$price1*100000)
mat_final$sales_total <- log(mat_final$sales_total*100000)
mat_final$price_total <- log(mat_final$price_total*100000)
write_dta(mat_final, "sdidres_hospital_all_vars_in_log.dta")
```
```{r}
setwd(file.path(directory_specific,"/Graphs/"))
country_list<-unique(mat_final[,1])
for (j in 1:length(country_list)){
  country_c <- country_list[j]
  # extract list of molecules for country_c
  molecule_list <- unique(mat_final[mat_final$country == country_c,2])
  mat_final_c <- mat_final[mat_final$country==country_c,]
  for (i in 1:length(molecule_list)) {
    molecule_d=molecule_list[i]
    mat_final_cd <- mat_final_c[mat_final_c$molecule==molecule_d,]
    
    plot_sales <- ggplot(data = mat_final_cd, aes(x = month)) + 
    geom_line(aes(y = sales_total, colour = "Treatment")) + 
    geom_line(aes(y = sales_control, colour = "Control")) +
    geom_vline(xintercept = as.numeric(unique(mat_final_cd$generic_entry)), linetype = "dashed", color = "green") +
    labs(title = paste("n controls", mat_final_cd$ncontrol_sales), x = "Month", y = "Sales") +
    scale_colour_manual(values = c("Treatment" = "blue", "Control" = "red")) +
    theme()
    ggsave(filename = file.path("SDID_log_noscale", paste0(country_c,"_", molecule_d, "_sales.png")), plot = plot_sales, width = 10, height = 6)
    
    plot_price <- ggplot(data = mat_final_cd, aes(x = month)) + 
    geom_line(aes(y = price_total, colour = "Treatment")) + 
    geom_line(aes(y = price_control, colour = "Control")) +
    geom_vline(xintercept = as.numeric(unique(mat_final_cd$generic_entry)), linetype = "dashed", color = "green") +
    labs(title = paste("n controls", mat_final_cd$ncontrol_price), x = "Month", y = "Price") +
    scale_colour_manual(values = c("Treatment" = "blue", "Control" = "red")) +
    theme()
    ggsave(filename = file.path("SDID_log_noscale", paste0(country_c,"_", molecule_d,"_price.png")), plot = plot_price, width = 10, height = 6)
  }
}
```
```{r}
file_path <- "C:/Users/rbm7796/Dropbox/FDC_IQVIA/Stata/Excel/molecule_info.xlsx"
molecule_data <- read.xlsx(file_path, sheet="molecule_list")

setwd(directory_data)
final_data<-read_dta("patent_data_match_molecule.dta")

final_data_temp<-filter(final_data, !is.na(molecule))
final_data_temp$molecule <- toupper(final_data_temp$molecule)

merged_data <- left_join(molecule_data, final_data_temp, by = "molecule", ignore)
colnames(merged_data)[colnames(merged_data) == "Ingredient"] <- "molecule_orangebook"
merged_data$molecule_orangebook<-toupper(merged_data$molecule_orangebook)

file_path <- "C:/Users/rbm7796/Dropbox/FDC_IQVIA/R_Marziyeh/Codes for Merging Datasets/molecules_no_match.xlsx"
nomatch_data <- read.xlsx(file_path)
nomatch_data$molecule <- toupper(nomatch_data$molecule)
nomatch_data$potential_match_orangebook <- 1

merged_data <- left_join(merged_data, nomatch_data, by = "molecule", ignore)

file_path <- "C:/Users/rbm7796/Dropbox/FDC_IQVIA/Stata/Excel/patent_data_need_revision.xlsx"
write.xlsx(merged_data, file = file_path)
```
```{r}
results_mat_temp <- results_mat %>% select(country,molecule,month,price_control,sales_control)
colnames(results_mat_temp)[colnames(results_mat_temp) == "price_control"] <- "price_SDID_log"
colnames(results_mat_temp)[colnames(results_mat_temp) == "sales_control"] <- "sales_SDID_log"

mat_for_export<-left_join(df, results_mat_temp, by = c("country", "molecule","month"))



setwd(directory_data)
data_temp2<-read_dta("data_cleaned_for_synthetic_molecule_with_sdidres_log.dta")

final_data_temp<-filter(final_data, !is.na(molecule))
final_data_temp$molecule <- toupper(final_data_temp$molecule)

merged_data <- left_join(molecule_data, final_data_temp, by = "molecule", ignore)
colnames(merged_data)[colnames(merged_data) == "Ingredient"] <- "molecule_orangebook"
merged_data$molecule_orangebook<-toupper(merged_data$molecule_orangebook)

file_path <- "C:\Users\rbm7796\Dropbox\FDC_IQVIA\Stata\Excel\synthetic_results_withranks.csv"
nomatch_data <- read.xlsx(file_path)
nomatch_data$molecule <- toupper(nomatch_data$molecule)
nomatch_data$potential_match_orangebook <- 1

merged_data <- left_join(merged_data, nomatch_data, by = "molecule", ignore)

file_path <- "C:/Users/rbm7796/Dropbox/FDC_IQVIA/Stata/Excel/patent_data_need_revision.xlsx"
write.xlsx(merged_data, file = file_path)
```









